# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e9107a2b9fdaf4a4884ff48d6fa5cd51306428defb8f7e877222011a00ffb646b6def15f0d0175582787b6385226debcaae23fb7ee8be6a31426ed4b32891ab

test:
  secret_key_base: e500e3b4486b91ae666a6ef73e20bdf235bcd803f1e005049d362dab87d7d5cf1c1f5ac249cae0252f1554b2552e8bb7b07ac320a199cde4c6e887a473e73077

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
